services:
  # TagoCore
  tcore:
    image: tagoio/tagocore:1.0.0-6-beta
    container_name: tcore
    restart: unless-stopped
    ports:
      - "8888:8888"
      - "1883:1883"
    volumes:
      - tcore-data:/root/.tagocore
      - ./decoders:/root/decoders
volumes:
  tcore-data:
